require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/environments/**/*.rb
    - config/initializers/simple_form*.rb
    - config/initializers/friendly_id.rb
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*

I18n/GetText/DecorateFunctionMessage:
  Enabled: false

I18n/GetText/DecorateString:
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/forms/**/*.rb
    - spec/interactors/**/*.rb
    - spec/requests/**/*.rb

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario]

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes
