require:
  - rubocop-rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/initializers/simple_form*.rb
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*

I18n/GetText/DecorateString:
  Exclude:
    - spec/**/*.rb

I18n/RailsI18n/DecorateString:
  Exclude:
    - spec/**/*.rb

RSpec/Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario]

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes
