version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/my_own_blog:cached
      - bundle_cache:/bundle_cache
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_PORT: 5000
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    stdin_open: true
    tty: true
    command: bin/docker-entrypoint

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:6.0-rc3-alpine

  sidekiq:
    depends_on:
      - web
      - postgres
      - redis
    build: .
    environment:
      REDIS_URL: redis://redis:6379/1
    command: sh -c './bin/wait-for web:5000 -- bundle exec sidekiq'

volumes:
  bundle_cache:
  pg_data:
