version: "3.7"

services:
  web:
    env_file: .env
    build: .
    volumes:
      - .:/my_own_blog:cached
      - bundle_cache:/bundle_cache
    ports:
      - ${RAILS_PORT}:${RAILS_PORT}
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    stdin_open: true
    tty: true
    command: bin/docker-entrypoint

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:6.0-rc3-alpine

  sidekiq:
    env_file: .env
    depends_on:
      - web
      - postgres
      - redis
    build: .
    command: sh -c "bin/wait-for web:${RAILS_PORT} -- bundle exec sidekiq"

volumes:
  bundle_cache:
  pg_data:
